check/urls.py
from django.conf.urls import patterns, include, url
from check import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fillme.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.add_new, name='new'),
    url(r'^archive/$', views.archive, name='archive'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^test/$', views.test, name='test'),


)

fillme/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'fillme.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/',include('check.urls', namespace='check')),
    
    

)

check/models.py
from datetime import date
from django.db import models


# Create your models here.


class Checkdetails(models.Model):
    name = models.CharField(max_length=100,verbose_name='Pay To',blank=True,null=True)
    total_ammount = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='TK',blank=True,null=True)
    ammount_in_word = models.CharField(max_length=100,blank=True,null=True)
    date = models.DateField(blank=True,null=True)

    def __unicode__(self):
    	return self.name

check/forms.py
from datetime import datetime
from django import forms
from crispy_forms.helper import FormHelper

from check.models import Checkdetails

class CheckDetailsForm(forms.ModelForm):
	name = forms.CharField(max_length=100)
	total_ammount = forms.DecimalField(max_digits=10, decimal_places=2)
	ammount_in_word = forms.CharField(max_length=100)
	date = forms.DateField()

	class Meta:
		model = Checkdetails
		

check/views.py
from datetime import datetime
from django.shortcuts import render, redirect, render_to_response
from django.http import HttpResponse ,HttpResponseRedirect
from django.template import RequestContext
from .forms import *


from check.models import *
# from check.forms import *
# Create your views here.





def index(request):
	return render(request, 'check/index.html', {})

def add_new(request):

    if request.method == 'POST':

        form = CheckDetailsForm(request.POST)

        if form.is_valid():
        	form.save(commit=True)
        	return redirect('/index/')
        else:
        	print form.errors

    else:
        form = CheckDetailsForm()

    return render(request,'check/new.html', { 'form':form })

def archive(request):
    info = Checkdetails.objects.all()
    context_dict = {"info": info}
    return render(request, 'check/archive.html', context_dict)


def contact(request):
    return render(request, 'check/contact.html', {})

def test(request):
    return render(request, 'check/test.html', {})

check/templates/check/archive.html
{% extends 'check/base.html' %}
{% load staticfiles %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'polls/css/style.css' %}"/> -->



{% block content %}
        <table class="table table-hover">
            <thead>
            <tr class="success">
                <th >Name</th>
                <th >Total (TK)</th>
                <th >Ammount in Word</th>
                <th >Date</th>
            </tr>
            </thead>
            <tbody>
            {% if info %}
                {% for i in info %}
                    <tr>
                    <td>
                        {{ i.name }}
                    </td>
                    <td>
                        {{i.total_ammount}}
                    </td>
                     <td>
                        {{i.ammount_in_word}}
                    </td>
                     <td>
                        {{i.date}}
                    </td>
                {% endfor %}
            {% else %}
                <td>Currently No item are available.</td>
            {% endif %}
            </tr>
            </tbody>
        </table>

{% endblock %}

check/templates/check/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap3 %}

<html lang="en">
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Check Filler</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'check/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'check/css/bootstrap.css' %}"/>
    
    
    <!-- <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet"> -->

    <!-- Custom styles for this template -->
    

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script>
    <script src="{% static 'check/js/modal.js' %}"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"/>
   

</head>

  <body>

  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url "check:index"%}">CHECK FILLER</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url "check:index"%}">HOME<span class="sr-only">(current)</span></a></li>
        <li><a href="{% url "check:new"%}">NEW</a></li>
        <li><a href="{% url "check:archive"%}">ARCHIVE</a></li>
        <li><a href="{% url "check:contact"%}">CONTACT</a></li>
        <li><a data-toggle="modal" href="#myModal1" >TEST</a></li>

      <!-- Modal -->
      <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
              <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
             
                  
                    Ariful Haque Rony<br>
                    lota nahar <br>
                    sabbir ahmed <br>
                  
                    <form action="/" method="post">
                    {% csrf_token %}
                    {{ form.name }}
                    <input type="submit" value="Submit" />
                </form>

            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save</button>
              <button style="background-color:#009871; border-color:#009871" class="btn btn-primary" id="printButton">Print</button>
            </div>
          </div>
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
          
      </ul>
  
    </div>
  </div>
</nav>

  <!-- Jumbotron -->
  <div class="jumbotron">
    {% block content %}{% endblock %} 
  </div>

  <!-- Footer -->
  <footer class="footer">
    <p>&copy; Rony 2015</p>
  </footer>
 

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

check/templates/check/contact.html
{% extends 'check/base.html' %}
{% load staticfiles %}




{% block content %}

<h1 style="color:#f1c40f">GALAXY </h1>

{% endblock %}

check/templates/check/index.html
{% extends 'check/base.html' %}
{% load staticfiles %}



{% block content %}
	<div class = index>
		<h1 style="color:#1abc9c">You</h1> 
		<p style="text-align:center;">are in right place.I am <strong style="color:#f1c40f">Check Filler</strong> and ready to fill your bank check in a <strong style="color:#f1c40f">Moment</strong>.</p>
		<!-- <p><a class="btn btn-primary btn-lg">Learn more</a></p> -->
	</div>


{% endblock %}

check/templates/check/new.html
{% extends 'check/base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

<!-- <link rel="stylesheet" type="text/css" href="{% static 'polls/css/form.css' %}"/> -->

{% block content %}

<!-- {% csrf_token %}
{{ form.non_field_errors }}
<div class="fieldWrapper">
    {{ form.subject.errors }}
    <label for="{{ form.subject.id_for_label }}">Email subject:</label>
    {{ form.name }}
</div>
<div class="fieldWrapper">
    {{ form.message.errors }}
    <label for="{{ form.message.id_for_label }}">Your message:</label>
    {{ form.total_ammount }}
</div>
<div class="fieldWrapper">
    {{ form.sender.errors }}
    <label for="{{ form.sender.id_for_label }}">Your email address:</label>
    {{ form.ammount_in_word }}
</div>
<div class="fieldWrapper">
    {{ form.cc_myself.errors }}
    <label for="{{ form.cc_myself.id_for_label }}">CC yourself?</label>
    {{ form.date }}
</div>
<input type="submit" value="Submit" /> -->
<div class="row">
     <div class="col-md-6 col-md-offset-3">

            <form class = "form-horizontyal" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
             
                <div class="col-lg-6 col-md-offset-4">
                {% buttons %}
                    <button  type="submit" class="btn btn-primary">
                        {% bootstrap_icon "star" %} Submit
                    </button>
                {% endbuttons %}
            </div>
            </form>
        </div>
</div>

{% endblock %}

check/templates/check/test.html
{% extends 'check/base.html' %}
{% load staticfiles %}

{% block mod %}

	<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}